// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYuLsdCxo_ceS904z4CNqVH_bJ1IF92eI',
    appId: '1:713659843769:web:1468de63e7cd7b221f8768',
    messagingSenderId: '713659843769',
    projectId: 'banco-bapiriya',
    authDomain: 'banco-bapiriya.firebaseapp.com',
    storageBucket: 'banco-bapiriya.firebasestorage.app',
    measurementId: 'G-W2F9BJ8G0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUVuZx6qdcT-V8z4_CSLfv9_OPJQkvjkc',
    appId: '1:713659843769:android:918602b233e9756f1f8768',
    messagingSenderId: '713659843769',
    projectId: 'banco-bapiriya',
    storageBucket: 'banco-bapiriya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnYDJhKksM7hVwO6uDV7xySzCuWnQgapM',
    appId: '1:713659843769:ios:bc049347ec9fb9381f8768',
    messagingSenderId: '713659843769',
    projectId: 'banco-bapiriya',
    storageBucket: 'banco-bapiriya.firebasestorage.app',
    iosBundleId: 'com.example.menulateral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnYDJhKksM7hVwO6uDV7xySzCuWnQgapM',
    appId: '1:713659843769:ios:bc049347ec9fb9381f8768',
    messagingSenderId: '713659843769',
    projectId: 'banco-bapiriya',
    storageBucket: 'banco-bapiriya.firebasestorage.app',
    iosBundleId: 'com.example.menulateral',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYuLsdCxo_ceS904z4CNqVH_bJ1IF92eI',
    appId: '1:713659843769:web:bf89379779cc4bff1f8768',
    messagingSenderId: '713659843769',
    projectId: 'banco-bapiriya',
    authDomain: 'banco-bapiriya.firebaseapp.com',
    storageBucket: 'banco-bapiriya.firebasestorage.app',
    measurementId: 'G-6PW88MZX36',
  );
}