"""Ajustando a Spring Boot

Revision ID: 30d36d6e9589
Revises: 
Create Date: 2025-02-21 22:31:32.168616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30d36d6e9589'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('account_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('balance',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(fsp=6),
               type_=sa.TIMESTAMP(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['account_number'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=mysql.DATETIME(fsp=6),
               nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.DOUBLE(asdecimal=True),
               nullable=True)
        batch_op.alter_column('account_number',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
